---
services:
  bbugyi200.dotfiles:
    build:
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/dotfiles:delegated
    working_dir: /dotfiles
