#!/bin/bash

###############################
#  Functions                  #
###############################
function source_if_exists() {
    [[ -f "$1" ]] && source "$1"
}

function insert_path() {
    local path_="$1"; shift
    local P="$1"; shift

    if _is_in_path "${path_}" "${P}"; then
        local new_path=
        for p in $(echo "${path_}" | tr ":" "\n"); do
            if [[ "${p}" == "${P}" ]]; then
                continue
            fi

            if [[ -n "${new_path}" ]]; then
                new_path="${new_path}":"${p}"
            else
                new_path="${p}"
            fi
        done

        path_="${new_path}"
    fi

    echo "${P}":"${path_}"
}

function dedup_path() {
    local path_="$1"; shift
    local new_path=

    for P in $(echo "${path_}" | tr ":" "\n"); do
        if ! _is_in_path "${new_path}" "${P}"; then
            if [[ -n "${new_path}" ]]; then
                new_path="${new_path}":"${P}"
            else
                new_path="${P}"
            fi
        fi
    done

    echo "${new_path}"
}

function _is_in_path() {
    local path_="$1"; shift
    local P="$1"; shift

    if [[ ":${path_}:" == *":${P}:"* ]]; then
        return 0
    else
        return 1
    fi
}


###############################
#  Source Commands            #
###############################
source_if_exists /etc/profile
source_if_exists /usr/bin/virtualenvwrapper_lazy.sh


###############################
#  Environment Variables      #
###############################
# >>> Conveniance Variables
export o=~/org
export BB=bbugyi.ddns.net
export DB="$HOME"/Sync
export DBB="$DB"/bin
export DBH="$DB"/home
export MOV=/mnt/hercules/plex/Movies
export MY_UUID=30634818
export TV=/mnt/hercules/plex/TV

# >>> Filesystem Paths
export PATH="$(insert_path "${PATH}" "/usr/sbin")"
export PATH="$(insert_path "${PATH}" "/sbin")"
export PATH="$(insert_path "${PATH}" "/usr/local/bin")"
export PATH="$(insert_path "${PATH}" "/usr/local/opt/gnu-getopt/bin")"
export PATH="$(insert_path "${PATH}" "${HOME}"/.cargo/bin)"
export PATH="$(insert_path "${PATH}" "${HOME}"/.poetry/bin)"
export MATLABPATH="$HOME/.matlab"

if [[ "$(id -u)" = 0 ]]; then
    export PATH="$(insert_path "${PATH}" "/root/.local/bin")"
fi

# >>> Miscellaneous
export ANSIBLE_NOCOWS=1
export BETTER_EXCEPTIONS=1
export EDITOR="$(command -v vim)"  # I set this so the crontab would use vim for editing
export FAV_CLIP_FILE="${HOME}"/Sync/var/notes/Journal/favs.txt
export FPP_DISABLE_SPLIT=1  # disables 'fpp' vim pane splitting
export FZF_DEFAULT_COMMAND='rg --files --hidden --smart-case'
export FZF_DEFAULT_OPTS='--reverse --height 40% --border'
M="$(printf "\u2709")"
export GO111MODULE=on
export LESS="${LESS}QR"
export MAILPATH="/var/mail/$USER? ${M} ${M} ${M} NEW MAIL IN /var/mail/$USER!!! ${M} ${M} ${M}"
export MCFLY_KEY_SCHEME=vim
export MCFLY_LIGHT=TRUE
export PAGER="less"
export PYTHONBREAKPOINT="pudb.set_trace"
export QT_QPA_PLATFORMTHEME="qt5ct"  # Fixes: missing okular icons
export RECENTLY_EDITED_FILES_LOG="$HOME"/Sync/var/recently_edited_files.log
export RIPGREP_CONFIG_PATH="$HOME"/.config/rgrc
export RUST_SRC_PATH="$HOME"/Sync/var/projects/rust/src
export SHELLCHECK_OPTS="-e SC1090 -e SC1091 -e SC1117 -e SC2001 -e SC2016 -e SC2046 -e SC2059 -e SC2129 -e SC2155 -e SC2162"
export SHV_SHELL_HISTORY_ROOT="${HOME}"/Sync/var/logs/shell-history
export TERM=tmux-256color
export WORKON_HOME=~/.virtualenvs
export XDG_CONFIG_HOME="$HOME"/.config
export ZIM_CONFIG_DIR="${HOME}"/.local/share/chezmoi/dot_config
export ZIM_ZSHRC_DIR="${HOME}"/.local/share/chezmoi

if [[ "$(uname -a)" == *"Darwin"* ]]; then
    export AT_WORK=true
    export DATE="gdate"
    export GREP="ggrep"
    export LS="gls"
    export PATH="$(insert_path "${PATH}" /opt/local/bin)"
    export PATH="$(insert_path "${PATH}" /opt/homebrew/bin)"
    export SED="gsed"
else
    export DATE="date"
    export GREP="grep"
    export LS="ls"
    export SED="sed"

    rust_version="$(rustc --version | perl -anE 'print $F[1]')"
    export PATH="$(insert_path "${PATH}" /opt/rust-bin-"${rust_version}"/bin)"
fi

# Fixes "perl: warning: Setting locale failed." errors when using SSH to
# connect to bugyidesk at work.
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8


###########################
#  Start X Window System  #
###########################
if [[ -z "$DISPLAY" ]] && [[ $(tty) = /dev/tty1 ]] && [[ "$(id -u)" != 0 ]]; then
    exec startx
fi


# MUST remain at bottom of file. Otherwise, other paths are prepended to $PATH
# somehow.
export PATH="$(insert_path "${PATH}" "$HOME/.local/bin")"
export PATH="$(insert_path "${PATH}" "$HOME/bin")"
export PATH="$(insert_path "${PATH}" "$HOME/.dynamic-colors/bin")"
export PATH="$(insert_path "${PATH}" "$HOME/.flamegraph")"
export PATH="$(insert_path "${PATH}" "${HOME}"/.tmp/bin)"
export PATH="$(insert_path "${PATH}" "${HOME}"/.gems/bin)"
export PATH="$(insert_path "${PATH}" /usr/local/go/bin)"
export PATH="$(insert_path "${PATH}" "${HOME}"/go/bin)"
export PATH="$(insert_path "${PATH}" "${HOME}"/.nix-profile/bin)"

export PYTHONPATH="$(insert_path "${PYTHONPATH}" "${HOME}"/.local/bin)"

export LIBRARY_PATH="$(dedup_path "${LIBRARY_PATH}")"
export PATH="$(dedup_path "${PATH}")"
export PYTHONPATH="$(dedup_path "${PYTHONPATH}")"
export LESS="$(python3 -c "import sys; print(''.join(set('${LESS}')))")"

export GEM_HOME="${HOME}"/.gems

source_if_exists "$HOME/.cargo/env"
source_if_exists "$HOME/.profile.local"

# HACK: So `source ~/.profile` always exits successfully (i.e. with an exit
# code of 0) if we make it to this point.
test 0
