default_query_group: "today"
saved_query_groups:
  today:
    default: "open"
    queries:
      inbox: "o @INBOX"
      late: "o due<0d"
      yesterday: "$1d p>0"
      done: "$0d p>0"
      open: &today "o due=0d"
      tomorrow: &tomorrow "o due=1d"
      week: &week "o due>0d due<=7d @W"
      quarter: &quarter "o due>0d due<=91d @Q"
      year: &year "o due>0d due<=1y @Y"
      olympiad: &olympiad "o due>0d due<=4y @O"
  days:
    default: "day-1"
    queries:
      day-1: *today
      day-2: *tomorrow
      day-3: "o due=2d"
      day-4: "o due=3d"
      day-5: "o due=4d"
      day-6: "o due=5d"
      day-7: "o due=6d"
      week: *week
      quarter: *quarter
      year: *year
  weeks_and_quarters:
    default: "week-1"
    queries:
      today: *today
      tomorrow: *tomorrow
      week-1: *week
      week-2: "o due>7d due<=14d @W"
      week-3: "o due>14d due<=21d @W"
      week-4: "o due>21d due<=28d @W"
      quarter-1: *quarter
      quarter-2: &quarter2 "o due>91d due<=182d @Q"
      quarter-3: &quarter3 "o due>182d due<=273d @Q"
      quarter-4: &quarter4 "o due>273d due<=364d @Q"
  quarters_and_years:
    default: "quarter-1"
    queries:
      week: *week
      quarter-1: *quarter
      quarter-2: *quarter2
      quarter-3: *quarter3
      quarter-4: *quarter4
      year-1: *year
      year-2: &year2 "o due>1y due<=2y @Y"
      year-3: &year3 "o due>2y due<=3y @Y"
      year-4: &year4 "o due>3y due<=4y @Y"
      olympiad: *olympiad
  years_and_olympiads:
    default: "year-1"
    queries:
      quarter-1: *quarter
      quarter-2: *quarter2
      year-1: *year
      year-2: *year2
      year-3: *year3
      year-4: *year4
      olympiad-1: *olympiad
      olympiad-2: "o due>4y due<=8y @O"
      olympiad-3: "o due>8y due<=12y @O"
      olympiad-4: "o due>12y due<=16y @O"
  done_by_day:
    default: "last-day-1"
    queries:
      last-week: &lastweek "$7d:1d p>0"
      last-day-1: "$1d p>0"
      last-day-2: "$2d p>0"
      last-day-3: "$3d p>0"
      last-day-4: "$4d p>0"
      last-day-5: "$5d p>0"
      last-day-6: "$6d p>0"
      last-day-7: "$7d p>0"
  done_by_week:
    default: "last-week-1"
    queries:
      last-month-1: "$28d:1d p>0"
      last-month-2: "$56d:29d p>0"
      last-week-1: *lastweek
      last-week-2: "$14d:8d p>0"
      last-week-3: "$21d:15d p>0"
      last-week-4: "$28d:22d p>0"
      last-week-5: "$35d:29d p>0"
      last-week-6: "$42d:36d p>0"
      last-week-7: "$49d:43d p>0"
      last-week-8: "$56d:50d p>0"
  done_by_quarter:
    default: "last-quarter-1"
    queries:
      last-year: "$364d:1d p>0"
      last-quarter-1: "$91d:1d p>0"
      last-quarter-2: "$182d:92d p>0"
      last-quarter-3: "$273d:183d p>0"
      last-quarter-4: "$364d:274d p>0"
