default_query_group: "today"
saved_query_groups:
  today:
    default: "today"
    queries:
      inbox: &inbox "o @INBOX"
      late: &late "o due<0d"
      today: &today "o due=0d"
      1w: &week "o due>0d due<=7d scope"
      1m: "o due>7d due<=35d scope>1"
      1q: &quarter "o due>35d due<=91d scope>2"
      1y: &year "o due>91d due<=1y scope>3"
      1o: &olympiad "o due>1y due<=4y scope>4"
      1t: "o due>4y due<=20y scope>5"
      someday: "o scope>6"
  work:
    default: "work_0d"
    queries:
      inbox: *inbox
      late: *late
      work_today: "o due=0d +w.*"
      work_1w: "o due>0d due<=7d scope +w.*"
      work_1m: "o due>7d due<=35d scope>1 +w.*"
      work_1q: "o due>35d due<=91d scope>2 +w.*"
      work_1y: "o due>91d due<=1y scope>3 +w.*"
      work_1o: "o due>1y due<=4y scope>4 +w.*"
      work_1t: "o due>4y due<=20y scope>5 +w.*"
      work_someday: "o scope>6 +w.*"
  days:
    default: "today"
    queries:
      1w: *week
      today: *today
      1d: &tomorrow "o due=1d"
      2d: "o due=2d"
      3d: "o due=3d"
      4d: "o due=4d"
      5d: "o due=5d"
      6d: "o due=6d"
      1q: *quarter
      1y: *year
  weeks_and_quarters:
    default: "1w"
    queries:
      today: *today
      1d: *tomorrow
      1w: *week
      2w: "o due>7d due<=14d scope"
      3w: "o due>14d due<=21d scope"
      4w: "o due>21d due<=28d scope"
      1q: *quarter
      2q: &quarter2 "o due>91d due<=182d scope>2"
      3q: &quarter3 "o due>182d due<=273d scope>2"
      4q: &quarter4 "o due>273d due<=364d scope>2"
  quarters_and_years:
    default: "1q"
    queries:
      1w: *week
      1q: *quarter
      2q: *quarter2
      3q: *quarter3
      4q: *quarter4
      1y: *year
      2y: &year2 "o due>1y due<=2y scope>3"
      3y: &year3 "o due>2y due<=3y scope>3"
      4y: &year4 "o due>3y due<=4y scope>3"
      1o: *olympiad
  years_and_olympiads:
    default: "1y"
    queries:
      1q: *quarter
      2q: *quarter2
      1y: *year
      2y: *year2
      3y: *year3
      4y: *year4
      1o: *olympiad
      2o: "o due>4y due<=8y scope>4"
      3o: "o due>8y due<=12y scope>4"
      4o: "o due>12y due<=16y scope>4"
  done_by_day:
    default: "xday-1"
    queries:
      xweek: &lastweek "$7d:1d p>0"
      xday-1: "$1d p>0"
      xday-2: "$2d p>0"
      xday-3: "$3d p>0"
      xday-4: "$4d p>0"
      xday-5: "$5d p>0"
      xday-6: "$6d p>0"
      xday-7: "$7d p>0"
      xday-0: "$0d p>0"
  done_by_week:
    default: "xweek-1"
    queries:
      xmonth-1: "$28d:1d p>0"
      xmonth-2: "$56d:29d p>0"
      xweek-1: *lastweek
      xweek-2: "$14d:8d p>0"
      xweek-3: "$21d:15d p>0"
      xweek-4: "$28d:22d p>0"
      xweek-5: "$35d:29d p>0"
      xweek-6: "$42d:36d p>0"
      xweek-7: "$49d:43d p>0"
      xweek-8: "$56d:50d p>0"
  done_by_quarter:
    default: "xquarter-1"
    queries:
      xyear: "$364d:1d p>0"
      xquarter-1: "$91d:1d p>0"
      xquarter-2: "$182d:92d p>0"
      xquarter-3: "$273d:183d p>0"
      xquarter-4: "$364d:274d p>0"
