default_query_group: "today"
saved_query_groups:
  today:
    default: "today"
    queries:
      inbox: &inbox "o @INBOX"
      late: &late "o due<0d"
      today: "o due=0d"
      week: &week "o due>0d due<=7d scope"
      month: "o due>0d due<=35d scope>1"
      quarter: &quarter "o due>0d due<=91d scope>2"
      year: &year "o due>0d due<=1y scope>3"
      olympiad: &olympiad "o due>0d due<=4y scope>4"
  work:
    default: "work_today"
    queries:
      inbox: *inbox
      late: *late
      work_today: "o due=0d +w.*"
      work_week: "o due>0d due<=7d scope +w.*"
      work_month: "o due>0d due<=35d scope>1 +w.*"
      work_quarter: "o due>0d due<=91d scope>2 +w.*"
      work_year: "o due>0d due<=1y scope>3 +w.*"
      work_olympiad: "o due>0d due<=4y scope>4 +w.*"
  days:
    default: "day-1"
    queries:
      week: *week
      day-1: &today "o due=0d"
      day-2: &tomorrow "o due=1d"
      day-3: "o due=2d"
      day-4: "o due=3d"
      day-5: "o due=4d"
      day-6: "o due=5d"
      day-7: "o due=6d"
      quarter: *quarter
      year: *year
  weeks_and_quarters:
    default: "week-1"
    queries:
      today: *today
      tomorrow: *tomorrow
      week-1: *week
      week-2: "o due>7d due<=14d scope"
      week-3: "o due>14d due<=21d scope"
      week-4: "o due>21d due<=28d scope"
      quarter-1: *quarter
      quarter-2: &quarter2 "o due>91d due<=182d scope>2"
      quarter-3: &quarter3 "o due>182d due<=273d scope>2"
      quarter-4: &quarter4 "o due>273d due<=364d scope>2"
  quarters_and_years:
    default: "quarter-1"
    queries:
      week: *week
      quarter-1: *quarter
      quarter-2: *quarter2
      quarter-3: *quarter3
      quarter-4: *quarter4
      year-1: *year
      year-2: &year2 "o due>1y due<=2y scope>3"
      year-3: &year3 "o due>2y due<=3y scope>3"
      year-4: &year4 "o due>3y due<=4y scope>3"
      olympiad: *olympiad
  years_and_olympiads:
    default: "year-1"
    queries:
      quarter-1: *quarter
      quarter-2: *quarter2
      year-1: *year
      year-2: *year2
      year-3: *year3
      year-4: *year4
      olympiad-1: *olympiad
      olympiad-2: "o due>4y due<=8y scope>4"
      olympiad-3: "o due>8y due<=12y scope>4"
      olympiad-4: "o due>12y due<=16y scope>4"
  done_by_day:
    default: "xday-1"
    queries:
      xweek: &lastweek "$7d:1d p>0"
      xday-1: "$1d p>0"
      xday-2: "$2d p>0"
      xday-3: "$3d p>0"
      xday-4: "$4d p>0"
      xday-5: "$5d p>0"
      xday-6: "$6d p>0"
      xday-7: "$7d p>0"
      xday-0: "$0d p>0"
  done_by_week:
    default: "xweek-1"
    queries:
      xmonth-1: "$28d:1d p>0"
      xmonth-2: "$56d:29d p>0"
      xweek-1: *lastweek
      xweek-2: "$14d:8d p>0"
      xweek-3: "$21d:15d p>0"
      xweek-4: "$28d:22d p>0"
      xweek-5: "$35d:29d p>0"
      xweek-6: "$42d:36d p>0"
      xweek-7: "$49d:43d p>0"
      xweek-8: "$56d:50d p>0"
  done_by_quarter:
    default: "xquarter-1"
    queries:
      xyear: "$364d:1d p>0"
      xquarter-1: "$91d:1d p>0"
      xquarter-2: "$182d:92d p>0"
      xquarter-3: "$273d:183d p>0"
      xquarter-4: "$364d:274d p>0"
