#!/bin/bash

#################################################################################
# Regression tests for chezmoi-managed SASE shell completions.                  #
#################################################################################

REPO_ROOT="${PWD}"

function set_up() {
  TEST_TMP="$(mktemp -d)"
  TEST_HOME="${TEST_TMP}/home"
  SOURCE_ROOT="${TEST_TMP}/source"
  HOOK_TEMPLATE="${SOURCE_ROOT}/.chezmoiscripts/run_onchange_after_zcompile_sase_completion.tmpl"

  mkdir -p \
    "${TEST_HOME}" \
    "${SOURCE_ROOT}/.chezmoiscripts" \
    "${SOURCE_ROOT}/dot_config/fish/completions" \
    "${SOURCE_ROOT}/dot_local/share/bash-completion/completions" \
    "${SOURCE_ROOT}/dot_zfunc"

  cp "${REPO_ROOT}/home/dot_config/fish/completions/sase.fish" \
    "${SOURCE_ROOT}/dot_config/fish/completions/sase.fish"
  cp "${REPO_ROOT}/home/dot_local/share/bash-completion/completions/sase" \
    "${SOURCE_ROOT}/dot_local/share/bash-completion/completions/sase"
  cp "${REPO_ROOT}/home/dot_zfunc/_sase" \
    "${SOURCE_ROOT}/dot_zfunc/_sase"
  cp "${REPO_ROOT}/home/.chezmoiscripts/run_onchange_after_zcompile_sase_completion.tmpl" \
    "${HOOK_TEMPLATE}"
}

function tear_down() {
  rm -rf "${TEST_TMP}"
}

function require_chezmoi() {
  if ! command -v chezmoi >/dev/null 2>&1; then
    bashunit::skip "chezmoi is required for completion source rendering"
    return 1
  fi
}

function require_zsh() {
  if ! command -v zsh >/dev/null 2>&1; then
    bashunit::skip "zsh is required for zcompile verification"
    return 1
  fi
}

function apply_completion_fixture() {
  chezmoi --source "${SOURCE_ROOT}" --destination "${TEST_HOME}" \
    apply --include files,dirs --force
}

function render_hook() {
  chezmoi --source "${SOURCE_ROOT}" --destination "${TEST_HOME}" \
    execute-template <"${HOOK_TEMPLATE}" >"${TEST_TMP}/zcompile-hook.sh"
}

function write_completion_startup_fragment() {
  {
    awk '
      /#  Startup Completion Scripts \/ Setup  #/ { capture = 1 }
      capture { print }
      /ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=/ { exit }
    ' "${REPO_ROOT}/home/dot_zshrc"
    grep -F 'autoload -U +X compinit && compinit -u' \
      "${REPO_ROOT}/home/dot_zshrc"
  } >"${TEST_TMP}/zsh-completion-startup.zsh"
}

function write_oh_my_zsh_fixture() {
  mkdir -p \
    "${TEST_HOME}/.cache" \
    "${TEST_HOME}/.oh-my-zsh/custom/completions" \
    "${TEST_HOME}/.zfunc"

  cat >"${TEST_HOME}/.oh-my-zsh/oh-my-zsh.sh" <<'ZSH'
ZSH_CUSTOM="${ZSH_CUSTOM:-${ZSH}/custom}"
fpath=("${ZSH_CUSTOM}/completions" $fpath)
autoload -Uz compinit
compinit -u -D
ZSH
}

function write_sase_completion_fixtures() {
  cat >"${TEST_HOME}/.zfunc/_sase" <<'ZSH'
#compdef sase
# Managed fixture: current grammar includes root --print-command.
_arguments '--print-command[print command]' '-p[print command]' '1: :((show\:Show))'
ZSH

  if [[ "${1}" == "with-conflict" ]]; then
    cat >"${TEST_HOME}/.oh-my-zsh/custom/completions/_sase" <<'ZSH'
#compdef sase
# Framework fixture: older grammar intentionally lacks root --print-command.
_arguments '1: :((show\:Old))'
ZSH
  fi
}

function run_zsh_completion_startup_probe() {
  local conflict_mode="${1}"

  write_completion_startup_fragment
  write_oh_my_zsh_fixture
  write_sase_completion_fixtures "${conflict_mode}"

  HOME="${TEST_HOME}" ZDOTDIR="${TEST_HOME}" zsh -f -c '
    source "$1"
    print -r -- "comp=${_comps[sase]:-UNSET}"
    autoload +X _sase
    print -r -- "source=${functions_source[_sase]:-UNSET}"
    print -r -- "first=${fpath[1]:-UNSET}"
  ' startup-probe "${TEST_TMP}/zsh-completion-startup.zsh"
}

function write_fake_sase_runtime() {
  local version="${1}"
  local grammar="${TEST_TMP}/grammar-${version}.bash"

  mkdir -p "${TEST_TMP}/bin"
  cat >"${grammar}" <<BASH
__sase_loaded_version() {
  printf '%s\n' '${version}'
}
_sase() {
  :
}
BASH

  if [[ ! -x "${TEST_TMP}/bin/sase" ]]; then
    cat >"${TEST_TMP}/bin/sase" <<'BASH'
#!/bin/bash
if [[ "${1:-}" == "completion" && "${2:-}" == "ensure" ]]; then
  printf '%s\n' "${SASE_FAKE_GRAMMAR:?}"
  exit 0
fi
exit 64
BASH
    chmod +x "${TEST_TMP}/bin/sase"
  fi

  printf '%s\n' "${grammar}"
}

function run_bash_loader_probe() {
  local grammar="${1}"
  local loader="${TEST_HOME}/.local/share/bash-completion/completions/sase"

  PATH="${TEST_TMP}/bin:${PATH}" SASE_FAKE_GRAMMAR="${grammar}" bash -c '
    source "$1"
    __sase_loaded_version
  ' bash-loader-probe "${loader}"
}

function test_apply_writes_completion_loaders_without_runtime_metadata() {
  require_chezmoi || return 0

  apply_completion_fixture

  assert_file_exists "${TEST_HOME}/.zfunc/_sase"
  assert_file_exists "${TEST_HOME}/.local/share/bash-completion/completions/sase"
  assert_file_exists "${TEST_HOME}/.config/fish/completions/sase.fish"
  assert_contains "Generated by sase completion loader zsh" \
    "$(cat "${TEST_HOME}/.zfunc/_sase")"
  assert_contains "completion ensure zsh" "$(cat "${TEST_HOME}/.zfunc/_sase")"
  assert_contains "--owner 'chezmoi'" "$(cat "${TEST_HOME}/.zfunc/_sase")"
  assert_file_not_exists "${TEST_HOME}/.sase/completion/stamp/bash.json"
  assert_file_not_exists "${TEST_HOME}/.sase/completion/stamp/fish.json"
  assert_file_not_exists "${TEST_HOME}/.sase/completion/stamp/zsh.json"
}

function test_apply_is_repeatable() {
  require_chezmoi || return 0

  apply_completion_fixture
  first_hash="$(sha256sum "${TEST_HOME}/.zfunc/_sase")"

  apply_completion_fixture
  second_hash="$(sha256sum "${TEST_HOME}/.zfunc/_sase")"

  assert_same "${first_hash}" "${second_hash}"
}

function test_hook_zcompiles_only_when_needed() {
  require_chezmoi || return 0
  require_zsh || return 0

  apply_completion_fixture
  render_hook

  first_output="$(HOME="${TEST_HOME}" bash "${TEST_TMP}/zcompile-hook.sh")"
  first_mtime="$(stat -c %Y "${TEST_HOME}/.zfunc/_sase.zwc")"
  second_output="$(HOME="${TEST_HOME}" bash "${TEST_TMP}/zcompile-hook.sh")"
  second_mtime="$(stat -c %Y "${TEST_HOME}/.zfunc/_sase.zwc")"

  sleep 1
  touch "${TEST_HOME}/.zfunc/_sase"
  third_output="$(HOME="${TEST_HOME}" bash "${TEST_TMP}/zcompile-hook.sh")"
  third_mtime="$(stat -c %Y "${TEST_HOME}/.zfunc/_sase.zwc")"

  assert_file_exists "${TEST_HOME}/.zfunc/_sase.zwc"
  assert_contains "loader bytecode refreshed" "${first_output}"
  assert_contains "loader bytecode is current" "${second_output}"
  assert_contains "loader bytecode refreshed" "${third_output}"
  assert_same "${first_mtime}" "${second_mtime}"
  assert_same "newer" "$(
    if [[ "${third_mtime}" -gt "${second_mtime}" ]]; then
      printf 'newer'
    else
      printf 'stale'
    fi
  )"
}

function test_repeated_apply_keeps_loader_stable_while_runtime_grammar_changes() {
  require_chezmoi || return 0

  apply_completion_fixture
  first_hash="$(sha256sum "${TEST_HOME}/.local/share/bash-completion/completions/sase")"
  first_grammar="$(write_fake_sase_runtime v1)"

  assert_same "v1" "$(run_bash_loader_probe "${first_grammar}")"

  second_grammar="$(write_fake_sase_runtime v2)"
  apply_completion_fixture
  second_hash="$(sha256sum "${TEST_HOME}/.local/share/bash-completion/completions/sase")"

  assert_same "${first_hash}" "${second_hash}"
  assert_same "v2" "$(run_bash_loader_probe "${second_grammar}")"
}

function test_zsh_startup_loads_managed_sase_completion_with_framework_conflict() {
  require_zsh || return 0

  output="$(run_zsh_completion_startup_probe with-conflict)"

  assert_contains "comp=_sase" "${output}"
  assert_contains "source=${TEST_HOME}/.zfunc/_sase" "${output}"
  assert_contains "first=${TEST_HOME}/.zfunc" "${output}"
}

function test_zsh_startup_loads_managed_sase_completion_without_conflict() {
  require_zsh || return 0

  output="$(run_zsh_completion_startup_probe without-conflict)"

  assert_contains "comp=_sase" "${output}"
  assert_contains "source=${TEST_HOME}/.zfunc/_sase" "${output}"
  assert_contains "first=${TEST_HOME}/.zfunc" "${output}"
}
