return {
	"Raimondi/delimitMate",
	"dylon/vim-antlr",
	"godlygeek/tabular",
	"google/vim-searchindex",
	"honza/vim-snippets",
	"tpope/vim-abolish",
	"tpope/vim-commentary",
	"tpope/vim-dispatch",
	"tpope/vim-fugitive",
	"tpope/vim-repeat",
	"tpope/vim-scriptease",
	"tpope/vim-surround",
	"tpope/vim-unimpaired",
	"tpope/vim-vinegar",
	"rcarriga/nvim-notify",
}
