return {
	"Raimondi/delimitMate",
	"L3MON4D3/cmp-luasnip-choice",
	"google/vim-searchindex",
	"honza/vim-snippets",
	"mhinz/vim-startify",
	"tpope/vim-abolish",
	"tpope/vim-commentary",
	"tpope/vim-dispatch",
	"tpope/vim-fugitive",
	"tpope/vim-repeat",
	"tpope/vim-scriptease",
	"tpope/vim-surround",
	"tpope/vim-unimpaired",
	"tpope/vim-vinegar",
}
