file_group_map:
  day:
    - "{days[0].year}/{yyyymmdd[0]}_day.zo"
  default:
    - "@day"
  done:
    - "{days[0].year}/{yyyymmdd[0]}_done.zo"
  habit:
    - "{days[1].year}/{yyyymmdd[1]}_habit.zo"
  vim:
    - "cfg/vimrc"
    - "cfg/zorg_actions.vim"
    - "cfg/go_to_related.vim"
template_pattern_map:
  ^(?P<date>[0-9]{4}[01][0-9][0-3][0-9])_habit\.zo$: habit_log_tmpl.zo
  ^(?P<date>[0-9]{4}[01][0-9][0-3][0-9])_done\.zo$: done_log_tmpl.zo
  ^(?P<date>[0-9]{4}[01][0-9][0-3][0-9])_day\.zo$: day_log_tmpl.zo
  ^(?P<date>[0-9]{4}[01][0-9][0-3][0-9])\.zo$: all_day_logs_tmpl.zo
  ^(?P<year_month>[0-9]{4}[01][0-9])\.zo$: month_logs_tmpl.zo
  ^(?P<year>[0-9]{4})\.zo$: year_logs_tmpl.zo
  ^prj_(?P<name>[a-z]+)\.zo$: prj_tmpl.zo
  ^act_(?P<name>[a-z]+)\.zo$: act_tmpl.zo
  ^act_(?P<name>[a-z]+)\.zo$: act_tmpl.zo
  ^.*_status\.zo$: status_tmpl.zo
  .*\.zo: default_tmpl.zo
vim_commands:
  - "source {zdir}/cfg/vimrc"
  - "edit"
