file_group_map:
  day:
    - "{days[0].year}/{yyyymmdd[0]}_day.zo"
  default:
    - "@day"
  done:
    - "{days[0].year}/{yyyymmdd[0]}_done.zo"
  habit:
    - "{days[1].year}/{yyyymmdd[1]}_habit.zo"
  vim:
    - "cfg/vimrc"
    - "cfg/zorg_actions.vim"
    - "cfg/go_to_related.vim"
  yest:
    - "{days[1].year}/{yyyymmdd[1]}_day.zo"
template_pattern_map:
  ^[0-9]{4}/(?P<date>[0-9]{4}[01][0-9][0-3][0-9])_habit\.zo$: zot/habit_log.zot
  ^[0-9]{4}/(?P<date>[0-9]{4}[01][0-9][0-3][0-9])_done\.zo$: zot/done_log.zot
  ^[0-9]{4}/(?P<date>[0-9]{4}[01][0-9][0-3][0-9])_day\.zo$: zot/day_log.zot
  ^[0-9]{4}/(?P<date>[0-9]{4}[01][0-9][0-3][0-9])\.zo$: zot/all_day_logs.zot
  ^(?P<year_month>[0-9]{4}[01][0-9])\.zo$: zot/month_logs.zot
  ^(?P<year>[0-9]{4})\.zo$: zot/year_logs.zot
  ^prj_(?P<name>[a-z]+)\.zo$: zot/prj.zot
  ^now_(?P<name>[a-z]+)\.zo$: zot/now.zot
  ^.*_status\.zo$: zot/status.zot
  ^query/links/(?P<name>[a-z0-9_/]+)_links\.zoq$: zot/links.zot
  ^query/(?P<project>[a-z0-9_]+)_reqs\.zoq$: zot/reqs_query.zot
  .*\.zoq: zot/query.zot
  .*\.zo: zot/default.zot
vim_commands:
  - "source {zdir}/cfg/vimrc"
  - "edit"
