# Generated by sase completion loader fish. Do not edit.

function __sase_loader_run
    for dir in $PATH
        set -l cmd "$dir/sase"
        if test -x "$cmd"
            if not string match -qr '/sase_[0-9]+/\.venv/bin/sase$' -- "$cmd"
                command "$cmd" $argv
                return $status
            end
        end
    end
    command sase $argv
end

if not set -q __SASE_COMPLETION_LOADER_ACTIVE
    set -g __SASE_COMPLETION_LOADER_ACTIVE 1
    set -l loader (status filename)
    set -l grammar (__sase_loader_run completion ensure fish --loader-path "$loader" --owner 'chezmoi' 2>/dev/null)
    if test -n "$grammar"; and test -r "$grammar"
        source "$grammar"
    end
    set -e __SASE_COMPLETION_LOADER_ACTIVE
end

functions -e __sase_loader_run
