name: CI
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ["${{ matrix.os }}"]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install prettier
        run: npm install -g prettier

      - uses: extractions/setup-just@v2

      - uses: astral-sh/setup-uv@v4

      - name: Run linters
        run: just lint
  test:
    runs-on: ["${{ matrix.os }}"]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - uses: extractions/setup-just@v2

      - uses: astral-sh/setup-uv@v4

      - name: Run tests
        run: just test
